map_type: costmap
footprint: [[-0.1, -0.28], [-0.1, 0.28], [0.8, 0.28], [0.8, -0.28]]
robot_base_frame: base_link
transform_tolerance: 0.3

obstacle_layer:
  enabled: true
  obstacle_range: 4.0     # maximum range sensor reading that whill result in an obstacle being put into the costmap
  raytrace_range: 5.0     # taytrace the freespace in front of the robot
  inflation_radius: 0.5 # distance around the obstacles with the same cost as obstacle
  track_unknown_space: false
  combination_method: 1
  inf_is_valid: true

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  3.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.0  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"

